### ISSUE TITLE
Add command to wapm.toml

### ISSUE THREAD

**Issue by MarkMcCaskey** [jedisct1/rsign2#1]
Hello!

Thanks for publishing this on wapm.io ;  We're about to publish an article about package signing (that I've been sitting on for 3 weeks at this point) and part of it shows using `rsign2` through wapm to generate a key that can be used to sign packages on wapm.  There's an issue with the currently published version on wapm.io though, wapm needs a "command" to actually run the wasm module:

We'd just need to add something like,
```toml
[[command]]
name = "rsign"
module = "rsign"
```

To the manifest to get this to work.

Anyways, here's what I think the manifest should could look like in full:

```toml
[package]
name = "jedisct1/rsign2"
version = "0.5.2"
description = "A command-line tool to sign files and verify signatures with Minisign"
readme = "README.md"
repository = "https://github.com/jedisct1/rsign2"
homepage = "https://github.com/jedisct1/rsign2"
license = "ISC"

[[module]]
name = "rsign"
source = "rsign.wasm"

[[command]]
name = "rsign"
module = "rsign"
```

If you could update that and republish it, we'd be very grateful!

By the way, we thank you and link to you and your projects in the article, so feel free to request edits (to the content or to what we link to!).  I'll send you an email with a link!  If you're interested feel free to respond or leave comments, otherwise we'll publish it in a few days.

Thanks!!
